"""Explicit D picture adoption and a read-only NEW-frame inventory.

    python edit/cutd_adoption.py
    python edit/cutd_adoption.py --json --dimensions

Folder arrival never adopts a take. Uncomment its D_NEW_TAKES line in edl_v3.py after review.
The inscription is one 400-frame delivery, shared by D07's burn and D08's forging front.
"""
import argparse
import json
from pathlib import Path


# Inclusive source ranges; these are D v2 frame numbers, including the inscription burn pre-roll.
NEW_PLATES = (
    ('D08', 'embers_D_inscription', 1680, 2079),
    ('D09', 'embers_D_forging', 2080, 2399),
    ('D10', 'embers_D_race', 2400, 2719),
    ('D12', 'embers_D_brink', 2960, 3199),
    ('D13', 'embers_D_vision', 3200, 3439),
    ('D14', 'embers_D_gap', 3440, 3519),
    ('D16', 'embers_D_trap', 3760, 4079),
    ('D17', 'falsedawn_brink', 4080, 4239),
    ('D18', 'embers_D_crowns', 4240, 4559),
    ('D19', 'falsedawn_twofires', 4560, 5039),
    ('D21b', 'embers_D_holdout', 5480, 5519),
    ('D22', 'embers_D_instep', 5680, 5839),
    ('D23', 'book_D_oldfire', 5840, 6079),
    ('D24', 'embers_D_unfinished', 6080, 6399),
    ('D27', 'falsedawn_watch', 7040, 7359),
    ('D28', 'falsedawn_truedawn', 7360, 7839),
    ('D31', 'book_lastleaf_open', 8320, 8639),
)
OPTIONAL_PLATES = (('D33', 'book_D_title', 8880, 9119),)


def baked_caption_ids(caption_rows, shots=None, planner=None):
    """Caption ids baked into explicitly selected, complete takes covering their whole caption window.

    This follows the assembler's metadata plan and need gate. It does not infer baked text from a filename,
    adopt a folder on arrival, or certify that a file decodes; decode/visual validation remains a render check.
    """
    if shots is None:
        import edl_v3 as EDL
        shots = EDL.D
    declared = [s for s in shots if any(t.get('baked_text') for t in s['takes'])]
    if not declared:
        return set()
    if planner is None:
        from assemble import plan_shot
        planner = plan_shot
    captions = {r['id']: r for r in caption_rows}
    baked = set()
    for shot in declared:
        plan = planner(shot, 'D', None)
        if plan['kind'] != 'take' or plan['have'] != shot['f1'] - shot['f0']:
            continue
        for ident in plan['take'].get('baked_text', ()):
            row = captions.get(ident)
            if row and shot['f0'] <= row['f_in'] < row['f_out'] <= shot['f1']:
                baked.add(ident)
    return baked


def availability(renders=None, dimensions=False):
    """Unique accepted RGB frame counts; optional dimensions read only the first selected image header.

    The assembler's index supplies its exact case-sensitive f_<integer>.png/jpg rules and PNG preference.
    An explicit renders path scans that catalogue only; adoption still reports the edit's declarations.
    """
    import assemble as AS
    import edl_v3 as EDL
    result = []
    for optional, catalog in ((False, NEW_PLATES), (True, OPTIONAL_PLATES)):
        for code, stem, first, last in catalog:
            take = EDL.T(stem, 0, 'exact', need=(first, last))
            dirs = [str(Path(renders) / stem)] if renders is not None else AS.chain(take, 'D')
            frames = {}
            for folder in dirs:
                AS._INDEX.pop(folder, None)  # a second inventory observes files that arrived since the first
                for frame, path in AS.index(folder).items():
                    frames.setdefault(frame, path)
            needed = set(range(first, last + 1))
            found = needed.intersection(frames)
            adopted = [s['code'] for s in EDL.D if any(t['stem'] == stem for t in s['takes'])]
            row = dict(row=code, stem=stem, first=first, last=last, needed=len(needed), available=len(found),
                       missing=len(needed - found), complete=found == needed, optional=optional,
                       adopted_rows=adopted, kind='plate')
            if dimensions and found:
                from PIL import Image
                frame = min(found)
                try:
                    with Image.open(frames[frame]) as image:
                        row['dimensions_sample'] = dict(frame=frame, width=image.width, height=image.height)
                except (OSError, ValueError) as error:
                    row['dimensions_sample'] = dict(frame=frame, error=type(error).__name__)
            result.append(row)
    result.append(dict(row='D07', stem='x1burn_D_drawnring', first=1680, last=1759, needed=80,
                       available=None, missing=None, complete=None, optional=False, adopted_rows=['D07'],
                       kind='generated', status='Generated by EDIT ring_burn; no layer folder required'))
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--renders', type=Path, help='scan an alternate render root without changing adoption')
    parser.add_argument('--json', action='store_true', help='print structured inventory')
    parser.add_argument('--dimensions', action='store_true', help='read the first available image header per stem')
    args = parser.parse_args(argv)
    rows = availability(args.renders, args.dimensions)
    if args.json:
        print(json.dumps(rows, indent=2))
    else:
        print('D NEW picture availability; folder counts do not adopt pictures.')
        print('stem                         need  have  miss  adoption / status')
        for row in rows:
            if row['kind'] == 'generated':
                print(f"{row['stem']:<28} {row['needed']:>4}     -     -  {row['status']}")
                continue
            adopted = ','.join(row['adopted_rows']) or 'not adopted'
            suffix = ' [optional]' if row['optional'] else ''
            sample = row.get('dimensions_sample')
            if sample:
                suffix += (f"; f{sample['frame']} {sample['width']}x{sample['height']}" if 'width' in sample
                           else f"; header error at f{sample['frame']}: {sample['error']}")
            print(f"{row['stem']:<28} {row['needed']:>4} {row['available']:>5} {row['missing']:>5}  {adopted}{suffix}")
    return rows


if __name__ == '__main__':
    main()
