"""THE LONG DAWN v3 - SOUND lane: write music/SFX_CREDITS.md from what the recipes actually use.

    python sound_credits_v3.py
    python sound_credits_v3.py --cuts D --out review/D_sound_credits.md

Every Freesound recording used by sound_recipes_{A,B,C}.py and ir_v3.py is listed with its licence (CC0 or CC-BY
only; NonCommercial and Sampling+ are refused by freesound_v3.licence_ok), its author and URL, and the exact
attribution line for CC-BY.  Every ElevenLabs generation (used or not) is logged with its prompt, seconds and
credits.
"""
import argparse
import importlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import freesound_v3 as F  # noqa: E402

MUSIC = os.path.dirname(HERE)
OUT = os.path.join(MUSIC, "SFX_CREDITS.md")


def walk(x, acc):
    if isinstance(x, dict):
        for v in x.values():
            walk(v, acc)
    elif isinstance(x, (list, tuple)):
        if x and isinstance(x[0], str) and ":" in x[0] and x[0].split(":")[0] in ("fs", "el", "sn"):
            acc.add(x[0])
        for v in x:
            walk(v, acc)


def selected_cuts(cuts):
    cuts = ''.join(cuts.split()).upper().replace(',', '')
    if not cuts or any(c not in 'ABCD' for c in cuts):
        raise ValueError('cuts must contain A, B, C or D')
    return ''.join(dict.fromkeys(cuts))


def used_refs(cuts='ABC'):
    cuts = selected_cuts(cuts)
    per_cut = {}
    installed = set()
    for cut in cuts:
        module = f"sound_recipes_{cut}"
        try:
            R = importlib.import_module(module)
        except ModuleNotFoundError as exc:
            if exc.name != module:
                raise                         # a broken installed recipe is not an empty inventory
            if cut == 'D':
                per_cut[cut] = set()           # D can be reviewed before its sound recipes exist
            continue
        acc = set()
        walk(R.RECIPES, acc)
        per_cut[cut] = acc
        installed.add(cut)
    if cuts == 'D' and not installed:
        return per_cut                         # no D effects means no recipe-owned reverb sources either
    import ir_v3
    acc = set()
    for sp in ir_v3.SPACES.values():
        for s in ([sp["src"]] if isinstance(sp["src"], str) else sp["src"]):
            acc.add("fs:" + s)
    per_cut["IR"] = acc
    return per_cut


def d_status(per_cut):
    return ["## Cut D sound status", "",
            "Cut D is a scaffold. This inventory covers installed D effects recipes; delivery can use a "
            "**STAND-IN** mix selected with `--audio` or `LD_D_AUDIO` before D's score exists. A supplied mix "
            "requires its own source credits; its filename does not establish attribution. Stand-in silence "
            "contains no borrowed recordings. An empty D inventory does not certify a supplied mix.", "",
            f"D recipe references: {len(per_cut.get('D', set()))}.", ""]


def main(cuts='ABC', out=OUT):
    cuts = selected_cuts(cuts)
    per_cut = used_refs(cuts)
    if cuts == 'D' and 'IR' not in per_cut:
        lines = ["# THE LONG DAWN v3: sound-effects credits (SOUND lane)", ""] + d_status(per_cut)
        lines += ["No D sound recipes are installed. No recording attribution has been inferred for a stand-in."]
        open(out, 'w').write('\n'.join(lines) + '\n')
        print(f'wrote {out}: D scaffold, no installed sound recipes')
        return
    allfs = sorted({r for s in per_cut.values() for r in s if r.startswith("fs:")}, key=lambda r: int(r[3:]))
    L = ["# THE LONG DAWN v3: sound-effects credits (SOUND lane)", "",
         "Generated by `music/src/sound_credits_v3.py` from the recipes, so it lists exactly what the effects stems use.",
         "Licences allowed: **CC0** and **CC-BY** (attribution below). NonCommercial and Sampling+ are refused by the "
         "search client. ElevenLabs (Starter plan, commercial licence): text-to-sound-effects only, with no voices and "
         "no music.", "",
         "## Freesound recordings", "",
         "| id | used in | licence | author | recording | source file |", "|---|---|---|---|---|---|"]
    if 'D' in cuts:
        L[5:5] = d_status(per_cut)
    attrib = []
    for r in allfs:
        sid = int(r[3:])
        s = F.info(sid)
        lic = F.licence_short(s.get("license"))
        where = ",".join(k for k, v in per_cut.items() if r in v)
        try:
            import sound_v3
            src = os.path.basename(sound_v3.src_path(r))
            kind = "original" if "_orig." in src else "HQ preview"
        except Exception:
            kind = "?"
        name = s.get("name", "").replace("|", "/")
        L.append(f"| [{sid}](https://freesound.org/s/{sid}/) | {where} | {lic} | {s.get('username', '')} | {name} | {kind} |")
        if lic.startswith("CC-BY"):
            ver = lic.split()[-1]
            attrib.append(f"- \"{name}\" by {s.get('username', '')} (https://freesound.org/s/{sid}/), licensed under "
                          f"CC BY {ver} (https://creativecommons.org/licenses/by/{ver}/). Edited: trimmed, filtered, "
                          f"levelled and mixed.")
    L += ["", "### Attribution (CC-BY)", ""] + (attrib or ["(none)"])
    # Sonniss
    sn = sorted({r for s in per_cut.values() for r in s if r.startswith("sn:")})
    try:
        picks = json.load(open(os.path.join(MUSIC, "sound", "sonniss_picks.json")))
    except Exception:
        picks = {}
    L += ["", "## Sonniss GDC 2026 Game Audio Bundle", "",
          "Licence: https://sonniss.com/gdc-bundle-license/ (royalty-free, commercial use, no attribution required; "
          "no AI/ML training).  Harvested picks (trimmed 48 kHz / 24-bit copies; the bundles were deleted after use):", ""]
    L += [f"- `{k}` {'(used: ' + ','.join(c for c, v in per_cut.items() if 'sn:' + k[:-4] in v) + ')' if any('sn:' + k[:-4] in v for v in per_cut.values()) else '(harvested, not used yet)'}: {v}"
          for k, v in sorted(picks.items())] or ["(none)"]
    # ElevenLabs
    try:
        log = json.load(open(os.path.join(MUSIC, "sound", "eleven_log.json")))
    except Exception:
        log = []
    usedel = {r[3:] for s in per_cut.values() for r in s if r.startswith("el:")}
    tot = sum(x.get("credits") or 0 for x in log)
    L += ["", "## ElevenLabs generations (every one, used or not)", "",
          f"Total logged: {len(log)} generations, {sum(x['seconds'] for x in log):.1f} s requested, "
          f"{tot} credits (budget 30,000). The account's usage counter updates late, so a generation can show 0 and "
          "the next one the sum; `eleven_v3.py credits` gives the live account total.", "",
          "| take | used | seconds | credits | prompt |", "|---|---|---|---|---|"]
    for x in log:
        tk = f"{x['tag']}_{x['take']:02d}"
        L.append(f"| {tk} | {'yes' if tk in usedel else ''} | {x['seconds']} | {x.get('credits')} | "
                 f"{x['prompt'].replace('|', '/')} |")
    L += ["", "## Measured impulse responses", "",
          "The effects' space uses measured responses from Freesound (listed above under `IR`), built by "
          "`music/src/ir_v3.py`. Voxengo's free IR set is not used, because it is modelled rather than measured."]
    open(out, "w").write("\n".join(L) + "\n")
    print(f"wrote {out}: {len(allfs)} Freesound recordings ({len(attrib)} CC-BY), {len(log)} ElevenLabs generations")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cuts', default='ABC', help='cut letters (default ABC; opt in with --cuts D)')
    parser.add_argument('--out', default=OUT)
    args = parser.parse_args()
    try:
        main(args.cuts, args.out)
    except ValueError as exc:
        parser.error(str(exc))
